version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: dev
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
      SERVER_NAME: "0.0.0.0:8000"
